version: '3.8'
services:
  server:
    image: server
    volumes:
      - database:/server/database
    ports:
      - "3001:3001"
  player:
    image: player
    ports:
      - "3000:3000"
  admin:
    image: admin
    ports:
      - "3002:3000"
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
volumes:
  database:
