version: '3.8'
services:
  server:
    image: server
    volumes:
      - database:/server/database

  player:
    image: player

  admin:
    image: admin

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"

volumes:
  database:
